# ~/.config/hypr/temas/One_dark.conf
# Cores profissionais One Dark

$bg_color       = 0xff5c6370  # One Dark Comment
$text_color     = 0xffabb2bf  # One Dark Foreground
$focused_bg     = 0xff61afef  # One Dark Blue
$focused_text   = 0xff1e2127  # One Dark Background
$unfocused_bg   = 0xff2c323c  # One Dark Darker
$unfocused_text = 0xff828997  # One Dark Gray
$urgent_bg      = 0xffe06c75  # One Dark Red
$urgent_text    = 0xff1e2127  # One Dark Background
