# # ~/.config/kitty/kitty.conf

# # Theme
# include theme/theme.conf
# include theme/tokyo_night.conf
# include configs/keybinds.conf

# Theme
include theme/theme.conf
include theme/tokyo_night.conf

# Keybinds
include configs/keybinds.conf

# Core configs
include configs/font.conf
include configs/performance.conf
include configs/window.conf
include configs/scroll.conf
include configs/mouse.conf
include configs/behavior.conf
include configs/layout.conf
include configs/remote.conf
include configs/shell.conf
include configs/misc.conf