# ~/.config/kitty/kitty.theme

# CURSOR
cursor                #c0caf5
cursor_text_color     #0c0a09
cursor_shape          beam
cursor_beam_thickness 1.0
cursor_underline_thickness 1.0
cursor_blink_interval 0

# CORES DOS LINKS/URLs
url_color #7aa2f7
url_style curly

# Aba ativa
active_tab_foreground   #c0caf5
active_tab_background   #0c0a09
active_tab_font_style   bold

# Abas inativas
inactive_tab_foreground #6272a4
inactive_tab_background #282a36
inactive_tab_font_style normal

# Barra de abas
tab_bar_background      #0c0a09
tab_bar_margin_color    #0c0a09