copy_on_select no
strip_trailing_spaces smart
select_by_word_characters @-./_~?&=%+#
click_interval -1.0
focus_follows_mouse no
default_pointer_shape beam
pointer_shape_when_grabbed arrow
mouse_hide_wait 0.0