# ~/.config/hypr/hyprland.conf

# Variáveis
$mod = SUPER
$term = kitty
$fileManager = dolphin

# Tema
source = ~/.config/hypr/temas/Tokyo_night.conf

# Configurações principais
source = ~/.config/hypr/configs/appearance.conf
source = ~/.config/hypr/configs/display.conf
source = ~/.config/hypr/configs/input.conf
source = ~/.config/hypr/configs/key_exec.conf
source = ~/.config/hypr/configs/keybinds.conf
source = ~/.config/hypr/configs/workspaces.conf
source = ~/.config/hypr/configs/exec.conf
source = ~/.config/hypr/configs/animations.conf
source = ~/.config/hypr/configs/misc.conf
source = ~/.config/hypr/configs/layout.conf
