# ~/.config/hypr/hypridle.conf
$lock_cmd = hyprctl dispatch global quickshell:lock & pidof qs quickshell hyprlock || hyprlock

general {
    lock_cmd = $lock_cmd
    before_sleep_cmd = hyprlock
    after_sleep_cmd = hyprctl dispatch global quickshell:lockFocus
}

listener {
    timeout = 300
    on-timeout = hyprlock
}

listener {
    timeout = 500
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}