# ~/.config/hypr/temas/Abyys.conf
# Cores profissionais Abyss

$bg_color       = 0xff6688cc  # Abyss Blue
$text_color     = 0xffffebc3  # Abyss Light
$focused_bg     = 0xff337acc  # Abyss Bright Blue
$focused_text   = 0xff000c18  # Abyss Dark
$unfocused_bg   = 0xff0f1419  # Abyss Background
$unfocused_text = 0xff6c7680  # Abyss Comment
$urgent_bg      = 0xffff6666  # Abyss Red
$urgent_text    = 0xff000c18  # Abyss Dark
