# ~/.config/hypr/temas/GruvBox.conf
# Cores profissionais Gruvbox

$bg_color       = 0xff504945  # Gruvbox Gray
$text_color     = 0xffebdbb2  # Gruvbox Light
$focused_bg     = 0xff458588  # Gruvbox Blue
$focused_text   = 0xff1d2021  # Gruvbox Dark
$unfocused_bg   = 0xff3c3836  # Gruvbox Dark Gray
$unfocused_text = 0xffa89984  # Gruvbox Light Gray
$urgent_bg      = 0xfffb4934  # Gruvbox Red
$urgent_text    = 0xff1d2021  # Gruvbox Dark
