# ~/.config/sway/config/keybinds.conf

# Setas direcionais
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# Mover com setas
bindsym $mod+Shift+Left move left 35px
bindsym $mod+Shift+Down move down 35px
bindsym $mod+Shift+Up move up 35px
bindsym $mod+Shift+Right move right 35px

# Layouts
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split
bindsym $mod+Shift+t layout stacking

# Fullscreen e floating
bindsym $mod+f fullscreen
bindsym $mod+Shift+space floating toggle
bindsym $mod+space focus mode_toggle