[General]
bookmarks=/home/sounier
lastDisplay=0
maximizedWindow=true
savedPaths=/home/sounier, /home/sounier, /home/sounier, /home/sounier, /home/sounier, /home/sounier, /home/sounier, /home/sounier, /home/sounier
windowGeometry=@Rect(488 53 464 499)
