# ~/.config/hypr/configs/appearance.conf

# BORDAS E GAPS
general {
    border_size = 1
    gaps_in = 3
    gaps_out = 6
    resize_on_border = true
    col.active_border = $focused_bg
    col.inactive_border = $unfocused_bg
}

# DECORAÇÕES
decoration {
    rounding = 8
    rounding_power = 2.0

    # Blur desativado por padrão
    blur {
        enabled = true
        size = 3
        passes = 1
        ignore_opacity = true
        new_optimizations = true
        special = false
        popups = true
        vibrancy = 0.1696
    }
}
