# ~/.config/hypr/configs/exec.conf

# Bar e notify
exec-once = waybar
exec-once = swaync

# Wallpaper
exec-once = ~/.config/hypr/scripts/wallpaper_front.sh

# Clipboard
exec-once = wl-paste -t text --watch clipman store

# Idle
exec-once = hypridle