# ~/.config/hypr/configs/input.conf

input {
    # CONFIGURAÇÕES DE TECLADO
    kb_layout = br
    kb_variant = abnt2
    repeat_delay = 300
    repeat_rate = 50

    # CONFIGURAÇÕES DE MOUSE
    accel_profile = flat
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    # focus_follows_mouse = no  →  follow_mouse = 0
    follow_mouse = 1

    # CONFIGURAÇÕES DE TOUCHPAD
    touchpad {
        tap-to-click = true
        natural_scroll = yes
        disable_while_typing = true
        middle_button_emulation = true
    }
}
