local main_mod = "SUPER"
local terminal = "kitty"

hl.bind(main_mod .. " + Z", hl.dsp.exec_cmd("swaync-client -t -sw"))
hl.bind(main_mod .. " + D", hl.dsp.exec_cmd("pkill wofi || wofi --show drun"))
hl.bind(main_mod .. " + F4", hl.dsp.window.close())
hl.bind(main_mod .. " + SHIFT + R", hl.dsp.exec_cmd("hyprctl reload"))
hl.bind(main_mod .. " + SHIFT + W", hl.dsp.exec_cmd("pkill waybar; waybar"))
hl.bind(main_mod .. " + L", hl.dsp.exec_cmd("hyprlock"))
hl.bind(main_mod .. " + E", hl.dsp.exit())
hl.bind(main_mod .. " + RETURN", hl.dsp.exec_cmd(terminal))
hl.bind(main_mod .. " + C", hl.dsp.exec_cmd("code --enable-features=UseOzonePlatform --ozone-platform=wayland"))
hl.bind(main_mod .. " + B", hl.dsp.exec_cmd("firefox --enable-features=UseOzonePlatform --ozone-platform=wayland"))
hl.bind(main_mod .. " + O", hl.dsp.exec_cmd("thunar >/dev/null 2>&1 &"))
hl.bind(main_mod .. " + S", hl.dsp.exec_cmd("steam >/dev/null 2>&1 &"))
hl.bind(main_mod .. " + V", hl.dsp.exec_cmd([[sh -c 'pgrep -x wofi >/dev/null && pkill wofi || cliphist list | wofi --dmenu | cliphist decode | wl-copy']]))
hl.bind(main_mod .. " + I", hl.dsp.exec_cmd("dbeaver >/dev/null 2>&1 &"))

hl.bind("Print", hl.dsp.exec_cmd("grim - | wl-copy && notify-send 'Screenshot' 'Copiado para clipboard'"))
hl.bind("SHIFT + Print", hl.dsp.exec_cmd("grim ~/Pictures/screenshot-$(date +%Y%m%d-%H%M%S).png && notify-send 'Screenshot' 'Salvo em ~/Pictures'"))
hl.bind(main_mod .. " + SHIFT + S", hl.dsp.exec_cmd("grim -g \"$(slurp)\" - | wl-copy && notify-send 'Screenshot' 'Área copiada'"))
hl.bind(main_mod .. " + SHIFT + Print", hl.dsp.exec_cmd("grim -g \"$(slurp)\" ~/Pictures/screenshot-area-$(date +%Y%m%d-%H%M%S).png && notify-send 'Screenshot' 'Área salva'"))

hl.bind(main_mod .. " + F8", hl.dsp.exec_cmd("pamixer -i 5 --allow-boost && notify-send 'Volume' \"$(pamixer --get-volume)%\""))
hl.bind(main_mod .. " + F7", hl.dsp.exec_cmd("pamixer -d 5 --allow-boost && notify-send 'Volume' \"$(pamixer --get-volume)%\""))
hl.bind(main_mod .. " + F6", hl.dsp.exec_cmd("pamixer --toggle-mute && notify-send 'Volume' \"$(pamixer --get-mute && echo 'Mutado' || echo 'Ativo')\""))

hl.bind(main_mod .. " + F3", hl.dsp.exec_cmd("brightnessctl set +5% && notify-send 'Brilho' \"$(brightnessctl get -P)%\""))
hl.bind(main_mod .. " + F2", hl.dsp.exec_cmd("brightnessctl set 5%- && notify-send 'Brilho' \"$(brightnessctl get -P)%\""))

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("pamixer -i 5 --allow-boost"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("pamixer -d 5 --allow-boost"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("pamixer --toggle-mute"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set +5%"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 5%-"), { locked = true, repeating = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

hl.define_submap("resize", function()
    hl.bind("h", hl.dsp.exec_cmd("hyprctl dispatch resize active -10 0"))
    hl.bind("j", hl.dsp.exec_cmd("hyprctl dispatch resize active 0 10"))
    hl.bind("k", hl.dsp.exec_cmd("hyprctl dispatch resize active 0 -10"))
    hl.bind("l", hl.dsp.exec_cmd("hyprctl dispatch resize active 10 0"))
    hl.bind("left", hl.dsp.exec_cmd("hyprctl dispatch resize active -10 0"))
    hl.bind("down", hl.dsp.exec_cmd("hyprctl dispatch resize active 0 10"))
    hl.bind("up", hl.dsp.exec_cmd("hyprctl dispatch resize active 0 -10"))
    hl.bind("right", hl.dsp.exec_cmd("hyprctl dispatch resize active 10 0"))
    hl.bind("return", hl.dsp.submap("reset"))
    hl.bind("escape", hl.dsp.submap("reset"))
    hl.bind(main_mod .. " + R", hl.dsp.submap("reset"))
end)

hl.bind(main_mod .. " + R", hl.dsp.submap("resize"))
