# ~/.config/hypr/configs/keybinds.conf

# Setas direcionais - foco
bind = $mod, Left,  movefocus, l
bind = $mod, Down,  movefocus, d
bind = $mod, Up,    movefocus, u
bind = $mod, Right, movefocus, r
bind = $mod, g, pseudo, # dwindle

# Mover janelas com setas
bind = $mod SHIFT, Left,  movewindow, l
bind = $mod SHIFT, Down,  movewindow, d
bind = $mod SHIFT, Up,    movewindow, u
bind = $mod SHIFT, Right, movewindow, r

bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow

# Layouts
# NOTA: "layout tabbed" e "layout stacking" não existem no Hyprland
# bind = $mod, w, layout tabbed      → SEM EQUIVALENTE NATIVO
# bind = $mod SHIFT, t, stacking     → SEM EQUIVALENTE NATIVO
bind = $mod, e, togglesplit          # equivalente ao "layout toggle split"

# Fullscreen e floating
bind = $mod, f,           fullscreen
bind = $mod SHIFT, Space, togglefloating
bind = $mod, Space,       togglefloating  # equivalente ao "focus mode_toggle"
